Actualizar template

diff --git a/template b/template
--- a/template
+++ b/template
@@ -1,7 +1,7 @@
-# Template file for 'Kasha-Installer'
-pkgname=Kasha-Installer
+# Template file for 'kasha-installer'
+pkgname=kasha-installer
 version=7.1
-revision=3
+revision=5
 build_style=gnu-configure
 hostmakedepends="pkg-config xxd"
 makedepends="gtk+3-devel"
@@ -25,41 +25,40 @@ do_build() {
 	GTK_CFLAGS=$(pkg-config --cflags gtk+-3.0)
 	GTK_LIBS=$(pkg-config --libs gtk+-3.0)
 	
-	# Buscar el header (puede estar en varios lugares)
-	if [ -f "include/neko_installer.h" ]; then
-		HEADER_DIR="include"
-	elif [ -f "src/neko_installer.h" ]; then
-		HEADER_DIR="src"
-	else
-		HEADER_DIR="."
-	fi
+	# Directorio de cabeceras (está en include/)
+	HEADER_DIR="include"
 	
 	CFLAGS="-fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -I${HEADER_DIR} ${GTK_CFLAGS}"
 	
 	# Crear directorio para objetos
 	mkdir -p obj
 	
-	# Compilar
-	for src in src/core/*.c src/ui/*.c; do
+	# Recopilar TODOS los archivos .c dentro de src/ (incluye core/, ui/, i18n/)
+	SOURCES=$(find src -name "*.c")
+	if [ -z "$SOURCES" ]; then
+		echo "ERROR: No se encontraron archivos fuente .c"
+		exit 1
+	fi
+	
+	# Compilar cada .c
+	for src in $SOURCES; do
 		obj="obj/$(basename ${src%.c}.o)"
-		cc $CFLAGS -c "$src" -o "$obj"
+		${CC} $CFLAGS -c "$src" -o "$obj"
 	done
 	
-	# Enlazar
-	cc -o neko_installer obj/*.o ${GTK_LIBS}
+	# Enlazar todos los objetos
+	${CC} -o neko_installer obj/*.o ${GTK_LIBS}
 }
 
 do_install() {
 	cd ${wrksrc}
 	
+	# Binario principal
 	vbin neko_installer
 	
+	# Recursos (si existen)
 	if [ -d data ]; then
 		vmkdir usr/share/kasha
 		cp -r data/* ${DESTDIR}/usr/share/kasha/
-	fi
-	
-	if [ -f Kasha-Installer.desktop ]; then
-		vinstall Kasha-Installer.desktop 644 usr/share/applications
 	fi
 }
